In [ ]:
#49:09
#複製17_6
import pandas as pd
df = pd.read_csv('學生成績.csv')  #讀進csv
df.index = df['學號']     #取學號欄的內容,覆蓋原本的索引
df1 = df.drop(columns='學號')  #移除學號欄
df1

In [ ]:
#53:39
df1['排名'] = df1['平均'].rank(method='min',ascending=False) #ascending=True表示升階,=False表示降階
df2 = df1.sort_values(by='平均',ascending=False)

In [ ]:
df2

In [ ]:
#1:03:40  #抓前十名
df2.iloc[:10]
#忘記iloc用法可以到17_4複習

     姓名  國文  英文   數學   地理   歷史   總分    平均    排名
學號
30  林向鈺  89  92   83   88  100  452  90.4   1.0
33  趙宛真  90  86   91   95   85  447  89.4   2.0
44  鍾俞禎  88  83  100  100   71  442  88.4   3.0
40  杜明延  95  86   77   86   94  438  87.6   4.0
7   黃詩妃  69  98   93   83   86  429  85.8   5.0
19  陳俊憲  97  98   87   52   88  422  84.4   6.0
1   黃心航  85  65   94   99   76  419  83.8   7.0
27  余宗儒  97  51   75  100   95  418  83.6   8.0
36  李政成  98  98   85   53   77  411  82.2   9.0
16  楊易政  91  89   82   90   57  409  81.8  10.0

In [ ]:
df2[10:]