In [ ]:
#1:36:02~1:40:08
import yfinance as yf
data =yf.download("AAPL", period="1mo") #近一個月的股票
data

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,,
2024-10-21,236.220108,236.479996,236.850006,234.449997,234.449997,36254500
2024-10-22,235.600800,235.860001,236.220001,232.600006,233.889999,38846600
2024-10-23,230.506393,230.759995,235.139999,227.759995,234.080002,52287000
2024-10-24,230.316620,230.570007,230.820007,228.410004,229.979996,31109500
2024-10-25,231.155685,231.410004,233.220001,229.570007,229.740005,38802300
2024-10-28,233.143494,233.399994,234.729996,232.550003,233.320007,36087100
2024-10-29,233.413193,233.669998,234.330002,232.320007,233.100006,35417200
2024-10-30,229.847122,230.100006,233.470001,229.550003,232.610001,47070900
2024-10-31,225.661728,225.910004,229.830002,225.369995,229.339996,64370100
2024-11-01,222.665024,222.910004,225.350006,220.270004,220.970001,65276700
2024-11-04,221.766006,222.009995,222.789993,219.710007,220.990005,44944500
2024-11-05,223.204422,223.449997,223.949997,221.139999,221.800003,28111300
2024-11-06,222.475235,222.720001,226.070007,221.190002,222.610001,54561100
2024-11-07,227.229996,227.479996,227.880005,224.570007,224.630005,42137700
2024-11-08,226.960007,226.960007,228.660004,226.410004,227.169998,38328800
2024-11-11,224.229996,224.229996,225.699997,221.500000,225.000000,42005600
2024-11-12,224.229996,224.229996,225.589996,223.360001,224.550003,40398300
2024-11-13,225.119995,225.119995,226.649994,222.759995,224.009995,48566200
2024-11-14,228.220001,228.220001,228.869995,225.000000,225.020004,44923900
2024-11-15,225.000000,225.000000,226.919998,224.270004,226.399994,47923700
2024-11-18,228.020004,228.020004,229.740005,225.169998,225.250000,44686000
2024-11-19,228.279999,228.279999,230.160004,226.660004,226.979996,36077500